package tn.insat.entities;
// Generated 26 janv. 2012 15:24:54 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Authors generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class Author  implements java.io.Serializable {
     /**
	 * Generated Serial Version 
	 */
	 private static final long serialVersionUID = 6814193466331912971L;
	 
	 private Integer authorId;
     private String name;
     private String country;
     private Set books = new HashSet(0);

    public Author() {
    }

	public Author(String name, String country, Set books) {
		super();
		this.name = name;
		this.country = country;
		this.books = books;
	}

	public Integer getAuthorId() {
		return authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set getBooks() {
		return books;
	}

	public void setBooks(Set books) {
		this.books = books;
	}

}


