package tn.insat.entities;
// Generated 26 janv. 2012 15:24:54 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class Book  implements java.io.Serializable {
    /**
	 * Generated Serial Version 
	 */
	 private static final long serialVersionUID = 6814193466331912971L;
     
	 private Integer bookId;
     private Publisher publisher;
     private String title;
     private Integer pages;
    
	private Set authors = new HashSet(0);

    public Book() {
    }

	public Book(Publisher publisher, String title, Integer pages, Set authors) {
		super();
		this.publisher = publisher;
		this.title = title;
		this.pages = pages;
		this.authors = authors;
	}

	public Integer getBookId() {
		return bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public Publisher getPublisher() {
		return publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getPages() {
		return pages;
	}

	public void setPages(Integer pages) {
		this.pages = pages;
	}

	public Set getAuthors() {
		return authors;
	}

	public void setAuthors(Set authors) {
		this.authors = authors;
	}
    
    

 



}


