package tn.insat.entities;
// Generated 26 janv. 2012 15:24:54 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Publishers generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class Publisher  implements java.io.Serializable {
    /**
	 * Generated Serial Version 
	 */
	 private static final long serialVersionUID = 6814193466331912971L;
	
     private Integer publisherId;
     private String name;
     private Set books = new HashSet(0);

    public Publisher() {
    }

	public Publisher(String name, Set books) {
		super();
		this.name = name;
		this.books = books;
	}

	public Integer getPublisherId() {
		return publisherId;
	}

	public void setPublisherId(Integer publisherId) {
		this.publisherId = publisherId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getBooks() {
		return books;
	}

	public void setBooks(Set books) {
		this.books = books;
	}

    
}


